routes/web.php
<?php

use Illuminate\Support\Facades\Route;
// Route::namespace('Admin')->group(function(){
//     route::get('admin',function(){
//         return 1;
//     });
// });

Route::namespace('Site')->group(function () {
    Route::get('/login', 'UserController@login')->name('site.login');
    Route::post('/login', 'UserController@login')->name('site.login');
    Route::post('/logout', 'UserController@logout')->name('site.logout');
    Route::get('/register', 'UserController@register')->name('site.register');
    Route::post('/register', 'UserController@register')->name('site.register');

    Route::get('/', 'HomeController@index')->name('home');

    Route::get('/danh-muc-bai-viet/{slug}', 'ContentController@categoryContent')->name('categoryContent');
    Route::get('/chi-tiet-bai-viet/{slug}', 'ContentController@detailContent')->name('detailContent');
    Route::get('/page/{page_id}', 'HomeController@page')->name('home.page');
    Route::get('/tim-kiem', 'ProductController@search')->name('search');
    Route::get('/listProductByCategory/{category_slug}', 'ProductController@listProductByCategory')->name('product');
    Route::get('/productDetail/{slug}', 'ProductController@productDetail')->name('detailProduct');
    Route::get('/certificate', 'CertificateController@index')->name('certificate');
    Route::get('/detailCertificate/{certificate_slug}', 'CertificateController@detailCertificate')->name('detailCertificate');
    Route::get('/feedback', 'FeedbackController@index')->name('feedback');
    Route::get('/list-file', 'HomeController@listFile')->name('file');
    Route::get('/video', 'HomeController@listVideo')->name('video');
    Route::get('/quang-cao', 'QcController@index')->name('qc');
    Route::get('/chi-tiet-quang-cao/{id}', 'QcController@detailQc')->name('detailQc');
});
Route::namespace('Admin')->prefix('admin')->group(function () {
    Route::get('/login', 'LoginController@view')->name('login');
    Route::post('/logout', 'LoginController@logout')->name('admin.logout');
    Route::post('/checkLogin', 'LoginController@checkLogin')->name('checkLogin');
    Route::get('/logOut', 'LoginController@logout')->name('logout');
});

Route::prefix('admin')->namespace('Admin')->name('admin.')->middleware('checkLoginAdmin')->group(function () {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/page/{page_id}', 'PageController@page')->name('page');
    Route::get('/nextPage/{page_id}', 'PageController@nextPage')->name('nextPage');
    Route::get('/prevPage/{page_id}', 'PageController@prevPage')->name('prevPage');

    Route::prefix('categoryProduct')->name('categoryProduct.')->group(function () {
        Route::get('/', 'CategoryProductController@index')->name('index');
        Route::get('/edit/{categoryProduct_id}', 'CategoryProductController@edit')->name('edit');
        Route::post('/store', 'CategoryProductController@store')->name('store');
        Route::PUT('/update/{categoryProduct_id}', 'CategoryProductController@update')->name('update');
        Route::delete('/delete/{categoryProduct_id}', 'CategoryProductController@delete')->name('delete');
    });
    Route::prefix('product')->name('product.')->group(function () {
        Route::get('/', 'ProductController@index')->name('index');
        Route::get('/create', 'ProductController@create')->name('create');
        Route::get('/edit/{product_id}', 'ProductController@edit')->name('edit');
        Route::get('/page/{page_id}', 'ProductController@page')->name('page');
        Route::post('/store', 'ProductController@store')->name('store');
        Route::post('/storeAddInCategory/{category_id}', 'ProductController@storeAddInCategory')->name('storeAddInCategory');

        Route::PUT('/update/{product_id}', 'ProductController@update')->name('update');
        Route::delete('/delete/{product_id}', 'ProductController@delete')->name('delete');
    });


    Route::prefix('categoryContent')->name('categoryContent.')->group(function () {
        Route::get('/', 'CategoryContentController@index')->name('index');
        Route::get('/edit/{categoryContent_id}', 'CategoryContentController@edit')->name('edit');
        Route::post('/store', 'CategoryContentController@store')->name('store');
        Route::PUT('/update/{categoryContent_id}', 'CategoryContentController@update')->name('update');
        Route::delete('/delete/{categoryContent_id}', 'CategoryContentController@delete')->name('delete');
    });
    Route::prefix('content')->name('content.')->group(function () {
        Route::get('/', 'ContentController@index')->name('index');
        Route::get('/create', 'ContentController@create')->name('create');
        Route::get('/edit/{Content_id}', 'ContentController@edit')->name('edit');
        Route::get('/page/{page_id}', 'ContentController@page')->name('page');
        Route::post('/store', 'ContentController@store')->name('store');
        Route::post('/storeAddInCategory/{category_id}', 'ContentController@storeAddInCategory')->name('storeAddInCategory');

        Route::PUT('/update/{Content_id}', 'ContentController@update')->name('update');
        Route::delete('/delete/{Content_id}', 'ContentController@delete')->name('delete');
    });

    Route::prefix('certificate')->name('certificate.')->group(function () {
        Route::get('/', 'CertificateController@index')->name('index');
        Route::get('/page/{page_id}', 'CertificateController@page')->name('page');
        Route::get('/create', 'CertificateController@create')->name('create');
        Route::get('/edit/{certificate_id}', 'CertificateController@edit')->name('edit');
        Route::get('/editItem/{item_id}', 'CertificateController@editItem')->name('editItem');
        Route::post('/store', 'CertificateController@store')->name('store');
        Route::post('/addItem', 'CertificateController@addItem')->name('addItem');
        Route::PUT('/update/{certificate_id}', 'CertificateController@update')->name('update');
        Route::PUT('/updateItem/{item_id}', 'CertificateController@updateItem')->name('updateItem');
        Route::delete('/delete/{certificate_id}', 'CertificateController@delete')->name('delete');
        Route::delete('/deleteItem/{item_id}', 'CertificateController@deleteItem')->name('deleteItem');
    });
    Route::prefix('feedback')->name('feedback.')->group(function () {
        Route::get('/', 'FeedbackController@index')->name('index');
        Route::get('/page/{page_id}', 'FeedbackController@page')->name('page');

        Route::get('/edit/{feedback_id}', 'FeedbackController@edit')->name('edit');
        Route::post('/store', 'FeedbackController@store')->name('store');
        Route::PUT('/update/{feedback_id}', 'FeedbackController@update')->name('update');
        Route::delete('/delete/{feedback_id}', 'FeedbackController@delete')->name('delete');
    });
    Route::prefix('file')->name('file.')->group(function () {
        Route::get('/', 'FileController@index')->name('index');
        Route::get('/page/{page_id}', 'FileController@page')->name('page');

        Route::get('/edit/{id}', 'FileController@edit')->name('edit');
        Route::get('/edit-file/{id}', 'FileController@editFile')->name('edit_file');
        Route::post('/store', 'FileController@store')->name('store');
        Route::post('/store-file', 'FileController@storeFile')->name('store_file');
        Route::PUT('/update/{id}', 'FileController@update')->name('update');
        Route::PUT('/update-file/{id}', 'FileController@updateFile')->name('update_file');
        Route::delete('/delete/{id}', 'FileController@delete')->name('delete');
        Route::delete('/delete-file/{id}', 'FileController@deleteFile')->name('delete_file');
        Route::get('/list-file/{category_file_id}', 'FileController@listFile')->name('list_file');
    });
    Route::prefix('video')->name('video.')->group(function () {
        Route::get('/', 'VideoController@index')->name('index');
        Route::get('/edit/{id}', 'VideoController@edit')->name('edit');
        Route::post('/store', 'VideoController@store')->name('store');
        Route::PUT('/update/{id}', 'VideoController@update')->name('update');
        Route::delete('/delete/{id}', 'VideoController@delete')->name('delete');
    });
    Route::prefix('adv')->name('advertisement.')->group(function () {
        Route::get('/', 'AdvController@index')->name('index');
        Route::get('/edit/{id}', 'AdvController@edit')->name('edit');
        Route::post('/store', 'AdvController@store')->name('store');
        Route::PUT('/update/{id}', 'AdvController@update')->name('update');
        Route::delete('/delete/{id}', 'AdvController@delete')->name('delete');
    });

    Route::prefix('slider')->name('slider.')->group(function () {
        Route::get('/', 'SliderController@index')->name('index');
        Route::get('/edit/{slider_id}', 'SliderController@edit')->name('edit');
        Route::post('/store', 'SliderController@store')->name('store');
        Route::PUT('/update/{slider_id}', 'SliderController@update')->name('update');
        Route::PUT('/active/{slider_id}', 'SliderController@active')->name('active');
        Route::delete('/delete/{slider_id}', 'SliderController@delete')->name('delete');
    });
    Route::prefix('setting')->name('setting.')->group(function () {
        Route::get('/', 'SettingController@index')->name('index');
        Route::post('/store', 'SettingController@store')->name('store');
    });
});
// Route::get('/video', function () {
//     return view('site.video');
// })->name('video');
// Route::get('/quang-cao', function () {
//     return view('site.qc');
// })->name('qc');

app/Http/Controllers/Admin/CategoryProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helpers\Helpers;
use App\Http\Controllers\ControllerBase;
use GuzzleHttp\Client;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cookie;

class CategoryProductController extends ControllerBase
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        $token = Cookie::get('tokenLogin');
        $client = new Client();
        $data = $client->get($this->urlAPI() . "admin/categoryProduct", [
            'headers' => [
                'Authorization' => 'Bearer ' . $token,
                'Accept' => 'application/json',
            ],
        ]);
        $response = json_decode($data->getBody()->getContents(), true);
        $responseData = $response['data'];
        return view('admin.categoryProduct.index2', compact('responseData'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $data = $request->all();

        $token = $request->cookie('tokenLogin');

        $dataSend = Helpers::dataSend($request);


        $url = $this->urlAPI() . 'admin/categoryProduct/create';
        $client = new Client([
            'headers' => [
                'Authorization' => 'Bearer ' . $token,
                'Content-Type' => 'application/json',
            ],
        ]);
        $req = $client->post(
            $url,
            [
                'multipart' => $dataSend,

            ],
            // ['form_params']
        );

        $response = json_decode($req->getBody()->getContents(), true);
        if ($response['status'] == 1) {

            alert()->success($response['message']);
            return redirect()->route('admin.categoryProduct.index');
        } else {
            alert()->error($response['message'], '');
            return back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $token = Cookie::get('tokenLogin');
        $client = new Client();
        $data = $client->get($this->urlAPI() . 'admin/categoryProduct/edit/' . $id, [
            'headers' => [
                'Authorization' => 'Bearer ' . $token,
                'Accept' => 'application/json',
            ],
        ]);
        $response = json_decode($data->getBody()->getContents(), true);
        if ($response['status'] == 1) {
            $category_product = $response['data'];
            return [
                'data' => $category_product,
                'code' => 200,
                'action' => route('admin.categoryProduct.update', $id),
            ];
        } else {
            return [
                'code' => 500,
            ];
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $data = $request->all();

        $token = $request->cookie('tokenLogin');

        $dataSend = Helpers::dataSend($request);

        $url = $this->urlAPI() . 'admin/categoryProduct/update/' . $id;
        $client = new Client([
            'headers' => [
                'Authorization' => 'Bearer ' . $token,
                'Content-Type' => 'application/json',
            ],
        ]);
        $req = $client->post(
            $url,
            [
                'multipart' => $dataSend,

            ],
            // ['form_params']
        );

        $response = json_decode($req->getBody()->getContents(), true);
        if ($response['status'] == 1) {

            alert()->success($response['message']);
            return redirect()->route('admin.categoryProduct.index');
        } else {
            alert()->error($response['message'], '');
            return back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete($id)
    {
        try {

            $token = Cookie::get('tokenLogin');
            if (!empty($token)) {
                # code...

                $client = new Client();
                $data = $client->delete($this->urlAPI() . 'admin/categoryProduct/delete/' . $id, [
                    'headers' => [
                        'Authorization' => 'Bearer ' . $token,
                        'Accept' => 'application/json',
                    ],
                ]);
                $response = json_decode($data->getBody()->getContents(), true);
                // dd($response);
                if ($response['status'] == 1) {
                    alert()->success($response['message']);
                    return redirect()->route('admin.categoryProduct.index');
                } else {
                    alert()->warning($response['message']);
                    return back();
                }

                return redirect()->back();
            }

            return redirect()->route('login');
        } catch (\Throwable $th) {
            alert($th)->error('Danh mục đang có sản phẩm không thể xóa.');
            return back();
        }
    }
}

resources/views/admin/categoryProduct/index.blade.php
@extends('admin.layouts.app')
@section('title-page', 'Danh sách category')
@section('content')
    <section class="content">
        <div class="container-fluid">
            {{-- <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form action="" method="GET" id="formSearchData">
                                <div class="row d-flex align-items-end">
                                    <div class="col-12 col-md-2">
                                        <label>Tiêu đề</label>
                                        <div class="input-group">
                                            <input type="text" autocomplete="off" class="form-control" name="name"
                                                value="{{ request('name') }}" placeholder="Tiêu đề" id="startdatepicker">
                                        </div>
                                        <!-- input-group -->
                                    </div>


                                    <button class="btn btn-primary float-right ml-auto"
                                        style="height: 40px; float:right">Search</button>

                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div> --}}
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header d-flex align-items-center justify-content-between">
                            <h3 class="card-title">Danh sách sản phẩm</h3>
                            <div class="float-right ml-auto">
                                <a class="col-md-2 col-12" href="#" data-toggle="modal" data-target="#modalAddcategory">
                                    <button class="btn btn-primary btn-sm" style="">Thêm mới + </button>
                                </a>
                            </div>

                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="table" class="table table-bordered table-hover ">

                                <thead class="thead-light">
                                    <tr>
                                        <th >STT</th>
                                        <th >Tên danh mục sản phẩm</th>

                                        <th >Thao tác</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($responseData['data'] as $index => $category)
                                        <tr>
                                            <th scope="row" style="vertical-align: middle ">{{ ++$index }}</th>
                                            <td style="vertical-align: middle ">{{ $category['name'] }}</td>
                                            <td style="vertical-align: middle ">
                                                <a href="{{ route('admin.categoryProduct.edit', $category['id']) }}"
                                                    class="btn btn-info btn-circle btn-sm editcategory">
                                                    <i class="fas fa-edit"></i>
                                                </a>

                                                <a class="btn btn-danger btn-circle btn-sm" href="" data-toggle="modal"
                                                    data-target="#delete{{ $category['id'] }}">
                                                    <i class="fas fa-trash"></i>

                                                </a>
                                            </td>
                                            <!-- delete Modal-->
                                            <div class="modal fade" id="delete{{ $category['id'] }}" tabindex="-1"
                                                role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title" id="exampleModalLabel">Bạn có chắn chắn
                                                                muốn
                                                                xoá?</h5>
                                                            <button class="close" type="button" data-dismiss="modal"
                                                                aria-label="Close">
                                                                <span aria-hidden="true">×</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">category: {{ $category['name'] }}</div>
                                                        <div class="modal-footer">
                                                            <button class="btn btn-secondary" type="button"
                                                                data-dismiss="modal">Huỷ</button>
                                                            <form
                                                                action="{{ route('admin.categoryProduct.delete', $category['id']) }}"
                                                                method="post">
                                                                @csrf
                                                                @method('delete')
                                                                <button class="btn btn-danger" href="">Xoá</button>
                                                            </form>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </tr>

                                    @endforeach

                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th scope="col">STT</th>
                                        <th scope="col">Tiêu đề</th>

                                        <th scope="col">Thao tác</th>
                                    </tr>

                                </tfoot>
                            </table>
                            <ul class="pagination justify-content-end">
                                @php
                                    $totalPage = $responseData['last_page'];
                                    $currentPage = $responseData['current_page'];

                                @endphp
                                <li class="page-item"><a class="page-link" href="#">Trước</a></li>
                                @for ($i = 1; $i <= $totalPage; $i++)
                                    <li class="page-item @if ($i==$currentPage) {{ 'active' }} @endif"><a class="page-link"
                                            href="{{ asset('/admin/san-pham/danh-sach/' . $i) }}">{{ $i }}</a>
                                    </li>
                                @endfor
                                <li class="page-item"><a class="page-link" href="#">Sau</a></li>
                            </ul>
                        </div>
                        <!-- /.card-body -->
                    </div>

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <div class="modal fade" id="modalAddcategory">
        <div class="modal-dialog modal-dialog-centered ">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Thêm mới category</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{ route('admin.categoryProduct.store') }}" method="post" id="formAddcategory"
                        enctype="multipart/form-data">
                        @csrf
                        <div class="card-body">
                            <div class="row">
                                <div class="col-12 ">
                                    <div class="form-group">
                                        <label for="inputTitle">Tên danh mục sản phẩm</label>
                                        <input type="text" class="form-control" id="inputTitle" required name="name"
                                            placeholder="Tên danh mục sản phẩm">
                                    </div>
                                </div>





                            </div>
                        </div>
                        <!-- /.card-body -->

                        <div class="modal-footer justify-content-between">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
                            <button type="submit" class="btn btn-primary">Lưu lại</button>
                        </div>
                    </form>
                </div>

            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
    <div class="modal fade" id="modalUpdatecategory">
        <div class="modal-dialog modal-dialog-centered ">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Cập nhật category</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="" method="post" id="formUpdatecategory" enctype="multipart/form-data">
                        @csrf
                        @method('put')
                        <div class="card-body">
                            <div class="row">
                                <div class="col-12 ">
                                    <div class="form-group">
                                        <label for="inputTitle">ên danh mục sản phẩm</label>
                                        <input type="text" class="form-control" id="inputTitle" required name="name"
                                            placeholder="ên danh mục sản phẩm">
                                    </div>
                                </div>




                            </div>
                        </div>
                        <!-- /.card-body -->

                        <div class="modal-footer justify-content-between">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
                            <button type="submit" class="btn btn-primary">Lưu lại</button>
                        </div>
                    </form>
                </div>

            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>
@endsection
@section('after-scripts')
    <script>
        $('.editcategory').click(function(e) {
            e.preventDefault();

            let href = $(this).attr('href');
            console.log(href);
            $.ajax({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                type: "GET",
                url: href,
                data: {
                },
                success: function(res) {
                    let category = res.data;
                    $('#formUpdatecategory input[name=name]').val(category.name);
                    $('#formUpdatecategory').attr('action', res.action);
                    $('#modalUpdatecategory').modal('show');
                },
                dataType: false
            });
        });
    </script>
@endsection