routes/web.php
<?php

use Illuminate\Support\Facades\Route;
// Route::namespace('Admin')->group(function(){
//     route::get('admin',function(){
//         return 1;
//     });
// });

Route::namespace('Site')->group(function () {
    Route::get('/login', 'UserController@login')->name('site.login');
    Route::post('/login', 'UserController@login')->name('site.login');
    Route::post('/logout', 'UserController@logout')->name('site.logout');
    Route::get('/register', 'UserController@register')->name('site.register');
    Route::post('/register', 'UserController@register')->name('site.register');

    Route::get('/', 'HomeController@index')->name('home');

    Route::get('/danh-muc-bai-viet/{slug}', 'ContentController@categoryContent')->name('categoryContent');
    Route::get('/chi-tiet-bai-viet/{slug}', 'ContentController@detailContent')->name('detailContent');
    Route::get('/page/{page_id}', 'HomeController@page')->name('home.page');
    Route::get('/tim-kiem', 'ProductController@search')->name('search');
    Route::get('/listProductByCategory/{category_slug}', 'ProductController@listProductByCategory')->name('product');
    Route::get('/productDetail/{slug}', 'ProductController@productDetail')->name('detailProduct');
    Route::get('/certificate', 'CertificateController@index')->name('certificate');
    Route::get('/detailCertificate/{certificate_slug}', 'CertificateController@detailCertificate')->name('detailCertificate');
    Route::get('/feedback', 'FeedbackController@index')->name('feedback');
    Route::get('/list-file', 'HomeController@listFile')->name('file');
    Route::get('/video', 'HomeController@listVideo')->name('video');
    Route::get('/quang-cao', 'QcController@index')->name('qc');
    Route::get('/chi-tiet-quang-cao/{id}', 'QcController@detailQc')->name('detailQc');
});
Route::namespace('Admin')->prefix('admin')->group(function () {
    Route::get('/login', 'LoginController@view')->name('login');
    Route::post('/logout', 'LoginController@logout')->name('admin.logout');
    Route::post('/checkLogin', 'LoginController@checkLogin')->name('checkLogin');
    Route::get('/logOut', 'LoginController@logout')->name('logout');
});

Route::prefix('admin')->namespace('Admin')->name('admin.')->middleware('checkLoginAdmin')->group(function () {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/page/{page_id}', 'PageController@page')->name('page');
    Route::get('/nextPage/{page_id}', 'PageController@nextPage')->name('nextPage');
    Route::get('/prevPage/{page_id}', 'PageController@prevPage')->name('prevPage');

    Route::prefix('categoryProduct')->name('categoryProduct.')->group(function () {
        Route::get('/', 'CategoryProductController@index')->name('index');
        Route::get('/edit/{categoryProduct_id}', 'CategoryProductController@edit')->name('edit');
        Route::post('/store', 'CategoryProductController@store')->name('store');
        Route::PUT('/update/{categoryProduct_id}', 'CategoryProductController@update')->name('update');
        Route::delete('/delete/{categoryProduct_id}', 'CategoryProductController@delete')->name('delete');
    });
    Route::prefix('product')->name('product.')->group(function () {
        Route::get('/', 'ProductController@index')->name('index');
        Route::get('/create', 'ProductController@create')->name('create');
        Route::get('/edit/{product_id}', 'ProductController@edit')->name('edit');
        Route::get('/page/{page_id}', 'ProductController@page')->name('page');
        Route::post('/store', 'ProductController@store')->name('store');
        Route::post('/storeAddInCategory/{category_id}', 'ProductController@storeAddInCategory')->name('storeAddInCategory');

        Route::PUT('/update/{product_id}', 'ProductController@update')->name('update');
        Route::delete('/delete/{product_id}', 'ProductController@delete')->name('delete');
    });


    Route::prefix('categoryContent')->name('categoryContent.')->group(function () {
        Route::get('/', 'CategoryContentController@index')->name('index');
        Route::get('/edit/{categoryContent_id}', 'CategoryContentController@edit')->name('edit');
        Route::post('/store', 'CategoryContentController@store')->name('store');
        Route::PUT('/update/{categoryContent_id}', 'CategoryContentController@update')->name('update');
        Route::delete('/delete/{categoryContent_id}', 'CategoryContentController@delete')->name('delete');
    });
    Route::prefix('content')->name('content.')->group(function () {
        Route::get('/', 'ContentController@index')->name('index');
        Route::get('/create', 'ContentController@create')->name('create');
        Route::get('/edit/{Content_id}', 'ContentController@edit')->name('edit');
        Route::get('/page/{page_id}', 'ContentController@page')->name('page');
        Route::post('/store', 'ContentController@store')->name('store');
        Route::post('/storeAddInCategory/{category_id}', 'ContentController@storeAddInCategory')->name('storeAddInCategory');

        Route::PUT('/update/{Content_id}', 'ContentController@update')->name('update');
        Route::delete('/delete/{Content_id}', 'ContentController@delete')->name('delete');
    });

    Route::prefix('certificate')->name('certificate.')->group(function () {
        Route::get('/', 'CertificateController@index')->name('index');
        Route::get('/page/{page_id}', 'CertificateController@page')->name('page');
        Route::get('/create', 'CertificateController@create')->name('create');
        Route::get('/edit/{certificate_id}', 'CertificateController@edit')->name('edit');
        Route::get('/editItem/{item_id}', 'CertificateController@editItem')->name('editItem');
        Route::post('/store', 'CertificateController@store')->name('store');
        Route::post('/addItem', 'CertificateController@addItem')->name('addItem');
        Route::PUT('/update/{certificate_id}', 'CertificateController@update')->name('update');
        Route::PUT('/updateItem/{item_id}', 'CertificateController@updateItem')->name('updateItem');
        Route::delete('/delete/{certificate_id}', 'CertificateController@delete')->name('delete');
        Route::delete('/deleteItem/{item_id}', 'CertificateController@deleteItem')->name('deleteItem');
    });
    Route::prefix('feedback')->name('feedback.')->group(function () {
        Route::get('/', 'FeedbackController@index')->name('index');
        Route::get('/page/{page_id}', 'FeedbackController@page')->name('page');

        Route::get('/edit/{feedback_id}', 'FeedbackController@edit')->name('edit');
        Route::post('/store', 'FeedbackController@store')->name('store');
        Route::PUT('/update/{feedback_id}', 'FeedbackController@update')->name('update');
        Route::delete('/delete/{feedback_id}', 'FeedbackController@delete')->name('delete');
    });
    Route::prefix('file')->name('file.')->group(function () {
        Route::get('/', 'FileController@index')->name('index');
        Route::get('/page/{page_id}', 'FileController@page')->name('page');

        Route::get('/edit/{id}', 'FileController@edit')->name('edit');
        Route::get('/edit-file/{id}', 'FileController@editFile')->name('edit_file');
        Route::post('/store', 'FileController@store')->name('store');
        Route::post('/store-file', 'FileController@storeFile')->name('store_file');
        Route::PUT('/update/{id}', 'FileController@update')->name('update');
        Route::PUT('/update-file/{id}', 'FileController@updateFile')->name('update_file');
        Route::delete('/delete/{id}', 'FileController@delete')->name('delete');
        Route::delete('/delete-file/{id}', 'FileController@deleteFile')->name('delete_file');
        Route::get('/list-file/{category_file_id}', 'FileController@listFile')->name('list_file');
    });
    Route::prefix('video')->name('video.')->group(function () {
        Route::get('/', 'VideoController@index')->name('index');
        Route::get('/edit/{id}', 'VideoController@edit')->name('edit');
        Route::post('/store', 'VideoController@store')->name('store');
        Route::PUT('/update/{id}', 'VideoController@update')->name('update');
        Route::delete('/delete/{id}', 'VideoController@delete')->name('delete');
    });
    Route::prefix('adv')->name('advertisement.')->group(function () {
        Route::get('/', 'AdvController@index')->name('index');
        Route::get('/edit/{id}', 'AdvController@edit')->name('edit');
        Route::post('/store', 'AdvController@store')->name('store');
        Route::PUT('/update/{id}', 'AdvController@update')->name('update');
        Route::delete('/delete/{id}', 'AdvController@delete')->name('delete');
    });

    Route::prefix('slider')->name('slider.')->group(function () {
        Route::get('/', 'SliderController@index')->name('index');
        Route::get('/edit/{slider_id}', 'SliderController@edit')->name('edit');
        Route::post('/store', 'SliderController@store')->name('store');
        Route::PUT('/update/{slider_id}', 'SliderController@update')->name('update');
        Route::PUT('/active/{slider_id}', 'SliderController@active')->name('active');
        Route::delete('/delete/{slider_id}', 'SliderController@delete')->name('delete');
    });
    Route::prefix('setting')->name('setting.')->group(function () {
        Route::get('/', 'SettingController@index')->name('index');
        Route::post('/store', 'SettingController@store')->name('store');
    });
});
// Route::get('/video', function () {
//     return view('site.video');
// })->name('video');
// Route::get('/quang-cao', function () {
//     return view('site.qc');
// })->name('qc');

app/Models/Contents.php
<?php

namespace App\Models;
use App\User;
use Illuminate\Database\Eloquent\Model;
use phpDocumentor\Reflection\DocBlock\Tags\Uses;

class Contents extends Model
{
    protected $table = 'contents';
    protected $primaryKey = 'id';
    protected $fillable = [
        'name',
        'user_id',
        'category_id',
        'title',
        'content',
        'status',
    ];

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }
    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
    public function listimage()
    {
        return $this->hasMany(ListImage::class, 'content_id');
    }
}

app/Http/Controllers/Site/ContentController.php
<?php

namespace App\Http\Controllers\Site;

use App\Helpers\Helpers;
use App\Http\Controllers\ControllerBase;
use GuzzleHttp\Client;

class ContentController extends ControllerBase
{
    //
    public function categoryContent($category_slug)
    {
        $client = new Client();

        $data = $client->get($this->urlAPI() . 'listContentByCategorySlug/' . $category_slug, [
            'headers' => [
                'Authorization' => 'Bearer ',
                'Accept' => 'application/json',
            ],
        ]);
        $response = json_decode($data->getBody()->getContents(), true);
        $dataContent = $response['data'];
        // dd($response);

        return view('site.post', compact('dataContent'));
    }
    public function detailContent($content_slug)
    {
        $client = new Client();

        $data = $client->get($this->urlAPI() . 'detailContent/' . $content_slug, [
            'headers' => [
                'Authorization' => 'Bearer ',
                'Accept' => 'application/json',
            ],
        ]);
        $response = json_decode($data->getBody()->getContents(), true);
        $content = $response['data'];
        $information = [
            'url' => route('detailProduct',$content_slug),
            'title' => $content['content']['title'],
            'description' => $content['content']['title'],
            'image' => Helpers::imageHome(),
        ];
        return view('site.detailPost', compact('content','information'));

    }
}

resources/views/admin/content/addProduct.blade.php
@extends('admin.layouts.app')
@section('title-page', 'Thêm mới sản phẩm')

@section('content')

    <div class="content">
        <div class="container">
            <div class="row">
                <div class="col-12 col-sm-12 col-md-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Thông tin sản phẩm</h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form action="{{ route('admin.product.store') }}" method="post" enctype="multipart/form-data">
                            @csrf
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="inputNameProduct">Tên sản phẩm</label>
                                            <input type="text" class="form-control" id="inputNameProduct" name="name"
                                                placeholder="Tên sản phẩm">
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="inputNameProduct">Loại sản phẩm</label>
                                            <select name="category_id" class="d-block select2 form-control" id="">
                                                @foreach ($category_products as $category)
                                                    <option value="{{ $category['id'] }}">
                                                        {{ $category['name'] }}
                                                    </option>

                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="inputSell">Giá bán</label>
                                            <input type="text" class="form-control formatPrice" id="inputSell" name="price"
                                                placeholder="Giá bán">
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="inputSale">Giá khuyến mãi</label>
                                            <input type="text" class="form-control formatPrice" id="inputSale"
                                                name="price_sale" placeholder="Giá khuyến mãi">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="exampleInputFile">Ảnh(Kích cỡ khuyên dùng >= 420*420)</label>
                                            <div class="image-input">
                                                <input type="file" accept="image/*" title="Kích cỡ khuyên dùng >= 420*420" id="exampleInputFile" name="image">
                                                <img src="" class="image-preview" style="max-width:100px">

                                            </div>

                                        </div>
                                    </div>
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="inputListImage">Danh sách ảnh(Kích cỡ khuyên dùng >= 420*420)</label>
                                            <div class="image-input">
                                                <input type="file" accept="image/*" title="Kích cỡ khuyên dùng >= 420*420" id="inputListImage" multiple
                                                    id="imageInput" name="list_images[]">
                                                <div class="list-image">

                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="inputInventory">Tồn kho</label>
                                            <input type="text" class="form-control formatPrice" id="inputInventory"
                                                name="total_inventory" placeholder="Tồn kho">
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="inputUserObject">Đối tượng sử dụng</label>
                                            <input type="text" class="form-control " id="inputUserObject" name="user_object"
                                                placeholder="Đối tượng sử dụng">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="inputUserManual">Hướng dẫn sử dụng</label>
                                            <textarea name="user_manual" class="form-control summernote" cols="4" rows="10">
                                            </textarea>
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label for="inputUsefulness">Công dụng</label>
                                            <textarea name="usefulness" class="form-control summernote" cols="4" rows="10">
                                        </textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12">
                                        <div class="form-group">
                                            <label for="">Mô tả sản phẩm</label>
                                            <textarea name="description" class="form-control summernote" cols="4" rows="10">
                                            </textarea>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12">
                                        <div class="form-group">
                                            <label for="">Chi tiết sản phẩm</label>
                                            <textarea name="content" class="form-control summernote" cols="4" rows="10">
                                            </textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Lưu</button>
                            </div>
                        </form>
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </div>
    </div>
@endsection
@section('after-css')
    <link rel="stylesheet" href="{{ asset('template/AdminLTE/plugins/summernote/summernote-bs4.min.css') }}">
@endsection
@section('after-scripts')
    <script src="{{ asset('template/AdminLTE/plugins/summernote/summernote-bs4.min.js') }}"></script>

    <script>
        $(function() {
            $('#imageInput').on('change', function() {
                $input = $(this);
                if ($input.val().length > 0) {
                    fileReader = new FileReader();
                    fileReader.onload = function(data) {
                        $('.image-preview').attr('src', data.target.result);
                    }
                    fileReader.readAsDataURL($input.prop('files')[0]);
                    $('.image-button').css('display', 'none');
                    $('.image-preview').css('display', 'block');
                    $('.change-image').css('display', 'block');
                }
            });
            $('.select2').select2();
            $('.change-image').on('click', function() {
                $control = $(this);
                $('#imageInput').val('');
                $preview = $('.image-preview');
                $preview.attr('src', '');
                $preview.css('display', 'none');
                $control.css('display', 'none');
                $('.image-button').css('display', 'block');
            });
            $('.formatPrice').priceFormat({
                prefix: '',
                centsLimit: 0,
                thousandsSeparator: '.'
            });
            // Summernote
            $('.summernote').summernote()
        })
    </script>

@endsection

resources/views/admin/content/addProductFeel.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{ asset('img/chapp_3.png') }}" type="image/x-icon">
    <title>Admin</title>
    <script src="{{ asset('js/jquery-2.2.0.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap-multiselect.js') }}"></script> <!-- Custom fonts for this template-->
    <link href="{{ asset('fontawesome/css/all.min.css') }}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link rel="stylesheet" href="{{ asset('css/admin.css') }}">
    <link href="{{ asset('css/admin.min.css') }}" rel="stylesheet">
    <link href="{{ asset('js/sweet-alert.js') }}" rel="stylesheet">

</head>

<body id="page-top">


    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        @include('admin/layout/menu')
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                @include('admin/layout/header')
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <div class="row">
                        <h2 class="text-left col-md-10 col-12">Thêm mới cảm nhận sản phẩm: </h2>
                    </div>

                    <form action="{{route('addProductFeel', ['id'=>$id])}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-row">
                            <div class="form-group col-md-6 col-12">
                                <label for="name">Tên khách hàng: </label>
                                <input type="text" class="form-control" id="name" name="name"
                                    placeholder="Tên khách hàng ..." required value="@if(isset($request->name)) {{$request->name}} @endif">
                            </div>
                            <div class="form-group col-md-6 col-12">
                                <label>Ảnh avatar:</label>
                                  <div class="image-input">
                                      <input type="file" accept="image/*" id="imageInput" name="image">
                                      <img src="" class="image-preview" style="max-width:100px">
                                     
                                  </div>
                              </div>
                        </div>
                        <div class="form-group">
                            <label for="content">Cảm nhận sản phẩm: </label><br>
                            <textarea name="post_content" class="form-control" id="content" cols="100%" rows="3"
                                placeholder="Cảm nhận sản phẩm..."></textarea>
                        </div>
                     

                        <div class="form-group">
                            <label for="video">Link video: </label><br>
                            <input type="text" class="form-control" id="video" name="video" placeholder="Link video cảm nhận ..." value="">
                        </div>
                       
                        <button type="submit" class="btn btn-secondary">Quay lại</button>
                        <a href="{{route('addProductFeel', ['id'=>$id])}}"><button type="submit" class="btn btn-primary">Thêm mới</button></a>
                    </form>

                    </nav>
                </div>

                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->



            <!-- Footer -->
            @include('admin.layout.footer')
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>



    <!-- Bootstrap core JavaScript-->
    {{-- <script src="{{ asset('js/jquery.min.js') }} "></script> --}}

    <!-- Custom scripts for all pages-->
    <script src="{{ asset('js/jquery.min.js') }} "></script>

    <!-- Custom scripts for all pages-->
    <script src="{{ asset('js/admin.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap.bundle.min.js') }}"></script>
    <script src="{{ asset('vendor/jquery/jquery.min.js') }}"></script>

    <script src="{{ asset('vendor/bootstrap/js/bootstrap.bundle.min.js') }} "></script>

    <!-- Core plugin JavaScript-->
    <script src="{{ asset('vendor/jquery-easing/jquery.easing.min.js') }}"></script>
    <script src="{{ asset('assets/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('vendor/sweetalert/sweetalert.all.js')}}"></script>
    @include('sweetalert::alert')


    <script type="text/javascript">
    CKEDITOR.replace('post_content');
        $(document).ready(function() {
            $('#example-dropUp').multiselect({
                enableFiltering: true,
                includeSelectAllOption: true,
                maxHeight: 500,
                dropUp: true
            });
        });
        $('#imageInput').on('change', function() {
            $input = $(this);
            if ($input.val().length > 0) {
                fileReader = new FileReader();
                fileReader.onload = function(data) {
                    $('.image-preview').attr('src', data.target.result);
                }
                fileReader.readAsDataURL($input.prop('files')[0]);
                $('.image-button').css('display', 'none');
                $('.image-preview').css('display', 'block');
                $('.change-image').css('display', 'block');
            }
        });

        $('.change-image').on('click', function() {
            $control = $(this);
            $('#imageInput').val('');
            $preview = $('.image-preview');
            $preview.attr('src', '');
            $preview.css('display', 'none');
            $control.css('display', 'none');
            $('.image-button').css('display', 'block');
        });

    </script>


</body>

</html>