routes/web.php
<?php

use Illuminate\Support\Facades\Route;
// Route::namespace('Admin')->group(function(){
//     route::get('admin',function(){
//         return 1;
//     });
// });

Route::namespace('Site')->group(function () {
    Route::get('/login', 'UserController@login')->name('site.login');
    Route::post('/login', 'UserController@login')->name('site.login');
    Route::post('/logout', 'UserController@logout')->name('site.logout');
    Route::get('/register', 'UserController@register')->name('site.register');
    Route::post('/register', 'UserController@register')->name('site.register');

    Route::get('/', 'HomeController@index')->name('home');

    Route::get('/danh-muc-bai-viet/{slug}', 'ContentController@categoryContent')->name('categoryContent');
    Route::get('/chi-tiet-bai-viet/{slug}', 'ContentController@detailContent')->name('detailContent');
    Route::get('/page/{page_id}', 'HomeController@page')->name('home.page');
    Route::get('/tim-kiem', 'ProductController@search')->name('search');
    Route::get('/listProductByCategory/{category_slug}', 'ProductController@listProductByCategory')->name('product');
    Route::get('/productDetail/{slug}', 'ProductController@productDetail')->name('detailProduct');
    Route::get('/certificate', 'CertificateController@index')->name('certificate');
    Route::get('/detailCertificate/{certificate_slug}', 'CertificateController@detailCertificate')->name('detailCertificate');
    Route::get('/feedback', 'FeedbackController@index')->name('feedback');
    Route::get('/list-file', 'HomeController@listFile')->name('file');
    Route::get('/video', 'HomeController@listVideo')->name('video');
    Route::get('/quang-cao', 'QcController@index')->name('qc');
    Route::get('/chi-tiet-quang-cao/{id}', 'QcController@detailQc')->name('detailQc');
});
Route::namespace('Admin')->prefix('admin')->group(function () {
    Route::get('/login', 'LoginController@view')->name('login');
    Route::post('/logout', 'LoginController@logout')->name('admin.logout');
    Route::post('/checkLogin', 'LoginController@checkLogin')->name('checkLogin');
    Route::get('/logOut', 'LoginController@logout')->name('logout');
});

Route::prefix('admin')->namespace('Admin')->name('admin.')->middleware('checkLoginAdmin')->group(function () {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/page/{page_id}', 'PageController@page')->name('page');
    Route::get('/nextPage/{page_id}', 'PageController@nextPage')->name('nextPage');
    Route::get('/prevPage/{page_id}', 'PageController@prevPage')->name('prevPage');

    Route::prefix('categoryProduct')->name('categoryProduct.')->group(function () {
        Route::get('/', 'CategoryProductController@index')->name('index');
        Route::get('/edit/{categoryProduct_id}', 'CategoryProductController@edit')->name('edit');
        Route::post('/store', 'CategoryProductController@store')->name('store');
        Route::PUT('/update/{categoryProduct_id}', 'CategoryProductController@update')->name('update');
        Route::delete('/delete/{categoryProduct_id}', 'CategoryProductController@delete')->name('delete');
    });
    Route::prefix('product')->name('product.')->group(function () {
        Route::get('/', 'ProductController@index')->name('index');
        Route::get('/create', 'ProductController@create')->name('create');
        Route::get('/edit/{product_id}', 'ProductController@edit')->name('edit');
        Route::get('/page/{page_id}', 'ProductController@page')->name('page');
        Route::post('/store', 'ProductController@store')->name('store');
        Route::post('/storeAddInCategory/{category_id}', 'ProductController@storeAddInCategory')->name('storeAddInCategory');

        Route::PUT('/update/{product_id}', 'ProductController@update')->name('update');
        Route::delete('/delete/{product_id}', 'ProductController@delete')->name('delete');
    });


    Route::prefix('categoryContent')->name('categoryContent.')->group(function () {
        Route::get('/', 'CategoryContentController@index')->name('index');
        Route::get('/edit/{categoryContent_id}', 'CategoryContentController@edit')->name('edit');
        Route::post('/store', 'CategoryContentController@store')->name('store');
        Route::PUT('/update/{categoryContent_id}', 'CategoryContentController@update')->name('update');
        Route::delete('/delete/{categoryContent_id}', 'CategoryContentController@delete')->name('delete');
    });
    Route::prefix('content')->name('content.')->group(function () {
        Route::get('/', 'ContentController@index')->name('index');
        Route::get('/create', 'ContentController@create')->name('create');
        Route::get('/edit/{Content_id}', 'ContentController@edit')->name('edit');
        Route::get('/page/{page_id}', 'ContentController@page')->name('page');
        Route::post('/store', 'ContentController@store')->name('store');
        Route::post('/storeAddInCategory/{category_id}', 'ContentController@storeAddInCategory')->name('storeAddInCategory');

        Route::PUT('/update/{Content_id}', 'ContentController@update')->name('update');
        Route::delete('/delete/{Content_id}', 'ContentController@delete')->name('delete');
    });

    Route::prefix('certificate')->name('certificate.')->group(function () {
        Route::get('/', 'CertificateController@index')->name('index');
        Route::get('/page/{page_id}', 'CertificateController@page')->name('page');
        Route::get('/create', 'CertificateController@create')->name('create');
        Route::get('/edit/{certificate_id}', 'CertificateController@edit')->name('edit');
        Route::get('/editItem/{item_id}', 'CertificateController@editItem')->name('editItem');
        Route::post('/store', 'CertificateController@store')->name('store');
        Route::post('/addItem', 'CertificateController@addItem')->name('addItem');
        Route::PUT('/update/{certificate_id}', 'CertificateController@update')->name('update');
        Route::PUT('/updateItem/{item_id}', 'CertificateController@updateItem')->name('updateItem');
        Route::delete('/delete/{certificate_id}', 'CertificateController@delete')->name('delete');
        Route::delete('/deleteItem/{item_id}', 'CertificateController@deleteItem')->name('deleteItem');
    });
    Route::prefix('feedback')->name('feedback.')->group(function () {
        Route::get('/', 'FeedbackController@index')->name('index');
        Route::get('/page/{page_id}', 'FeedbackController@page')->name('page');

        Route::get('/edit/{feedback_id}', 'FeedbackController@edit')->name('edit');
        Route::post('/store', 'FeedbackController@store')->name('store');
        Route::PUT('/update/{feedback_id}', 'FeedbackController@update')->name('update');
        Route::delete('/delete/{feedback_id}', 'FeedbackController@delete')->name('delete');
    });
    Route::prefix('file')->name('file.')->group(function () {
        Route::get('/', 'FileController@index')->name('index');
        Route::get('/page/{page_id}', 'FileController@page')->name('page');

        Route::get('/edit/{id}', 'FileController@edit')->name('edit');
        Route::get('/edit-file/{id}', 'FileController@editFile')->name('edit_file');
        Route::post('/store', 'FileController@store')->name('store');
        Route::post('/store-file', 'FileController@storeFile')->name('store_file');
        Route::PUT('/update/{id}', 'FileController@update')->name('update');
        Route::PUT('/update-file/{id}', 'FileController@updateFile')->name('update_file');
        Route::delete('/delete/{id}', 'FileController@delete')->name('delete');
        Route::delete('/delete-file/{id}', 'FileController@deleteFile')->name('delete_file');
        Route::get('/list-file/{category_file_id}', 'FileController@listFile')->name('list_file');
    });
    Route::prefix('video')->name('video.')->group(function () {
        Route::get('/', 'VideoController@index')->name('index');
        Route::get('/edit/{id}', 'VideoController@edit')->name('edit');
        Route::post('/store', 'VideoController@store')->name('store');
        Route::PUT('/update/{id}', 'VideoController@update')->name('update');
        Route::delete('/delete/{id}', 'VideoController@delete')->name('delete');
    });
    Route::prefix('adv')->name('advertisement.')->group(function () {
        Route::get('/', 'AdvController@index')->name('index');
        Route::get('/edit/{id}', 'AdvController@edit')->name('edit');
        Route::post('/store', 'AdvController@store')->name('store');
        Route::PUT('/update/{id}', 'AdvController@update')->name('update');
        Route::delete('/delete/{id}', 'AdvController@delete')->name('delete');
    });

    Route::prefix('slider')->name('slider.')->group(function () {
        Route::get('/', 'SliderController@index')->name('index');
        Route::get('/edit/{slider_id}', 'SliderController@edit')->name('edit');
        Route::post('/store', 'SliderController@store')->name('store');
        Route::PUT('/update/{slider_id}', 'SliderController@update')->name('update');
        Route::PUT('/active/{slider_id}', 'SliderController@active')->name('active');
        Route::delete('/delete/{slider_id}', 'SliderController@delete')->name('delete');
    });
    Route::prefix('setting')->name('setting.')->group(function () {
        Route::get('/', 'SettingController@index')->name('index');
        Route::post('/store', 'SettingController@store')->name('store');
    });
});
// Route::get('/video', function () {
//     return view('site.video');
// })->name('video');
// Route::get('/quang-cao', function () {
//     return view('site.qc');
// })->name('qc');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    //
    protected $table = 'product';
    protected $primaryKey = 'id';
    protected $fillable = [
        'name',
        'price',
        'price_sale',
        'image',
        'description',
        'strategic_vision'
    ];
    public function getImageAttribute($image)
    {
        if ($image == null) {
            return asset('/image_default/avatar_default.jpg');
        }
        return asset($image);
    }
    
    public function productFeel()
    {
        return $this->HasMany(ProductFeel::class, 'product_id');
    }
    public function relatedProduct()
    {
        return $this->HasMany(RelatedProduct::class, 'product_id');
    }
}

app/Http/Controllers/Api/ProductsController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\ControllerBase;
use Illuminate\Http\Request;

use GuzzleHttp\Client;
use Illuminate\Http\Response;

class ProductsController extends ControllerBase
{
    public function list_products($i){
        // try {
            $client = new Client([
                'headers' => [
                'Content-Type' => 'application/json',
            ],
            ]);
           
            $data = $client->get($this->urlAPI() . "list-product?page=" . $i);
            $response = json_decode($data->getBody()->getContents(), true);
            $listdata = $response['data'];
            return view('includes.product.danhSachSanPham', compact('listdata'));
            
        // } catch (\Throwable $th) {
        //     alert($th)->error('Hệ thống đang được bảo trì. Vui lòng thử lại sau!');
        //     return back();
        // }
    }

    public function products_detail($id){
        try {
            $client = new Client([
                'headers' => [
                'Content-Type' => 'application/json',
            ],
            ]);
           
            $data = $client->get($this->urlAPI() . "product-detail/$id");
            $response = json_decode($data->getBody()->getContents(), true);
            $listdata = $response['data'];
            return view('includes.product.sanPham', compact('listdata'));
            
        } catch (\Throwable $th) {
            alert($th)->error('Hệ thống đang được bảo trì. Vui lòng thử lại sau!');
            return back();
        }
    }

    public function list_products_index(){
        // try {
            $client = new Client([
                'headers' => [
                'Content-Type' => 'application/json',
            ],
            ]);
           
            $data = $client->get($this->urlAPI() . "list-product");
            $response = json_decode($data->getBody()->getContents(), true);
            $listdata = $response['data'];
            
            $datapolicy = $client->get($this->urlAPI() . "list-policy");
            $responsepolicy = json_decode($datapolicy->getBody()->getContents(), true);
            $listpolicy = $responsepolicy['data'];

            $dataevent = $client->get($this->urlAPI() . "list-event?page=1");
            $responseevent = json_decode($dataevent->getBody()->getContents(), true);
            $listevent = $responseevent['data'];

            $dataintroduce = $client->get($this->urlAPI() . 'list-introduce');
            $responseintroduce = json_decode($dataintroduce->getBody()->getContents(), true);
            $listintroduce = $responseintroduce['data'];

            $dataheadquarter = $client->get($this->urlAPI() . 'list-headquarter');
            $responseheadquarter = json_decode($dataheadquarter->getBody()->getContents(), true);
            $listheadquarter = $responseheadquarter['data'];

            return view('index', compact('listdata','listpolicy','listevent','listintroduce','listheadquarter'));
            
        // } catch (\Throwable $th) {
        //     alert($th)->error('Hệ thống đang được bảo trì. Vui lòng thử lại sau!');
        //     return back();
        // }
    }

    public function list_policy(){
        // try {
            $client = new Client([
                'headers' => [
                'Content-Type' => 'application/json',
            ],
            ]);
           
            $data = $client->get($this->urlAPI() . "list-policy");
            $response = json_decode($data->getBody()->getContents(), true);
            $listdata = $response['data'];
            return view('includes.policy', compact('listdata'));
            
        // } catch (\Throwable $th) {
        //     alert($th)->error('Hệ thống đang được bảo trì. Vui lòng thử lại sau!');
        //     return back();
        // }
    }

    public function list_event($i){
        // try {
            $client = new Client([
                'headers' => [
                'Content-Type' => 'application/json',
            ],
            ]);
           
            $data = $client->get($this->urlAPI() . "list-event?page=" . $i);
            $response = json_decode($data->getBody()->getContents(), true);
            $listdata = $response['data'];
            return view('includes.event.event', compact('listdata'));
            
        // } catch (\Throwable $th) {
        //     alert($th)->error('Hệ thống đang được bảo trì. Vui lòng thử lại sau!');
        //     return back();
        // }
    }

    public function event_detail($id){
        // try {
            $client = new Client([
                'headers' => [
                'Content-Type' => 'application/json',
            ],
            ]);
           
            $data = $client->get($this->urlAPI() . "detail-event/$id");
            $response = json_decode($data->getBody()->getContents(), true);
            $listdata = $response['data'];
            $data = $client->get($this->urlAPI() . "list-event?page=1");
            $response = json_decode($data->getBody()->getContents(), true);
            $listevent = $response['data'];
            return view('includes.event.event-detail', compact('listdata', 'listevent'));
            
        // } catch (\Throwable $th) {
        //     alert($th)->error('Hệ thống đang được bảo trì. Vui lòng thử lại sau!');
        //     return back();
        // }
    }

    public function CSKH(Request $request)
    {
        $body = [
            'phone' => $request->phone,
            'email' => $request->email,
        ];
        $input = json_encode($body);
        $url = $this->urlAPI() . 'create-contact';
        $client = new Client([
            'headers' => ['Content-Type' => 'application/json'],
        ]);
        $req = $client->post($url,
            ['body' => $input]
        );
        $response = json_decode($req->getBody()->getContents(), true);
        if ($response['status'] == 1) {
            alert()->success($response['message']);
            return back();
        } else {
            alert()->error($response['message']);
            return back();
        }
    }

    public function list_promotion(){
        // try {
            $client = new Client([
                'headers' => [
                'Content-Type' => 'application/json',
            ],
            ]);
           
            $data = $client->get($this->urlAPI() . "list-promotion");
            $response = json_decode($data->getBody()->getContents(), true);
            $listdata = $response['data'];
            return view('includes.promotion.promotion', compact('listdata'));
            
        // } catch (\Throwable $th) {
        //     alert($th)->error('Hệ thống đang được bảo trì. Vui lòng thử lại sau!');
        //     return back();
        // }
    }

    public function promotion_detail($id){
        try {
            $client = new Client([
                'headers' => [
                'Content-Type' => 'application/json',
            ],
            ]);
            $data = $client->get($this->urlAPI() . "promotion-detail/$id");
            $response = json_decode($data->getBody()->getContents(), true);
            $listdata = $response['data'];
            return view('includes.promotion.promotion-details', compact('listdata'));
            
        } catch (\Throwable $th) {
            alert($th)->error('Hệ thống đang được bảo trì. Vui lòng thử lại sau!');
            return back();
        }
    }

}

resources/views/admin/product/index.blade.php
@extends('admin.layouts.app')
@section('title-page', 'Danh sách sản phẩm')
@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form action="" method="GET" id="formSearchData">
                                <div class="row d-flex align-items-end">

                                    <div class="col-12 col-md-2">
                                        <label>Tên sản phẩm</label>
                                        <div class="input-group">
                                            <input type="text" autocomplete="off" class="form-control" name="name"
                                                value="{{ request('name') }}" placeholder="Tên sản phẩm" id="">
                                        </div>
                                        <!-- input-group -->
                                    </div>

                                    <div class="col-12 col-md-4">
                                        <label>Loại sản phẩm</label>
                                        <div class="input-group">
                                            <select name="category_id" class="select2 d-block form-control">
                                                <option value="">--Loại sản phẩm--</option>
                                                @foreach ($category_products as $cate)
                                                    @if ($cate['children'])
                                                        @foreach ($cate['children'] as $item)
                                                            <option value="{{ $item['id'] }}" @if($item['id'] == request('category_id')) selected @endif>{{ $cate['name'] }}--
                                                                {{ $item['name'] }}</option>

                                                        @endforeach
                                                    @else
                                                        <option value="{{ $cate['id'] }}" @if($cate['id'] == request('category_id')) selected @endif>{{ $cate['name'] }}</option>

                                                    @endif
                                                @endforeach
                                            </select>
                                        </div>
                                        <!-- input-group -->
                                    </div>
                                    <button class="btn btn-primary float-right ml-auto"
                                        style="height: 40px; float:right">Search</button>

                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header d-flex align-items-center justify-content-between">
                            <h3 class="card-title">Danh sách nhập kho</h3>
                            <div class="float-right  ml-auto">
                                <a class="col-md-2 col-12" href="{{ route('admin.product.create') }}">
                                    <button class="btn btn-primary btn-sm" style="">Thêm mới + </button>
                                </a>
                            </div>

                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">
                            <table id="" class="table table-bordered table-hover ">

                                <thead class="thead-light">
                                    <tr>
                                        <th scope="col">STT</th>
                                        <th scope="col" class="text-center">Ảnh</th>
                                        <th scope="col-2">Tên sản phẩm</th>
                                        <th scope="col-2">Loại sản phẩm</th>
                                        <th scope="col-2">Giá sản phẩm</th>
                                        <th scope="col-2">Giá khuyến mãi</th>
                                        <th scope="col">Thao tác</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($responseData['data'] as $index => $product)
                                        <tr>
                                            <th scope="row" style="vertical-align: middle ">{{ ++$index }}</th>
                                            <td class="products" style="vertical-align: middle "><img
                                                    src="{{ $product['image'] }}" width="60" class="object-fit-cover">
                                            </td>
                                            <td style="vertical-align: middle ">{{ $product['name'] }}</td>
                                            <td style="vertical-align: middle ">
                                                {{ !empty($product['category_product']) ? $product['category_product']['name'] : null }}
                                            </td>

                                            <td style="vertical-align: middle ">

                                                {{ number_format($product['price']) }} đ
                                            </td>
                                            <td style="vertical-align: middle ">
                                                @if ($product['price_sale'] != null)
                                                    {{ number_format($product['price_sale']) }} đ

                                                @endif
                                            </td>


                                            {{-- <td style="vertical-align: middle ">
                                            <a href="{{ asset('admin/san-pham/cam-nhan/' . $product['id']) }}"
                                                class="btn btn-info btn-circle btn-sm">
                                                <i class="fas fa-info-circle"></i>
                                            </a>
                                        </td> --}}
                                            <td style="vertical-align: middle ">
                                                <a href="{{ route('admin.product.edit', $product['id']) }}"
                                                    class="btn btn-info btn-circle btn-sm">
                                                    <i class="fas fa-edit"></i>
                                                </a>

                                                <a class="btn btn-danger btn-circle btn-sm" href="" data-toggle="modal"
                                                    data-target="#delete{{ $product['id'] }}">
                                                    <i class="fas fa-trash"></i>

                                                </a>
                                            </td>
                                            <!-- delete Modal-->
                                            <div class="modal fade" id="delete{{ $product['id'] }}" tabindex="-1"
                                                role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                <div class="modal-dialog" role="document">
                                                    <div class="modal-content">
                                                        <div class="modal-header">
                                                            <h5 class="modal-title" id="exampleModalLabel">Bạn có chắn chắn
                                                                muốn
                                                                xoá?</h5>
                                                            <button class="close" type="button" data-dismiss="modal"
                                                                aria-label="Close">
                                                                <span aria-hidden="true">×</span>
                                                            </button>
                                                        </div>
                                                        <div class="modal-body">Sản phẩm: {{ $product['name'] }}</div>
                                                        <div class="modal-footer">
                                                            <button class="btn btn-secondary" type="button"
                                                                data-dismiss="modal">Huỷ</button>
                                                            <form
                                                                action="{{ route('admin.product.delete', $product['id']) }}"
                                                                method="post">
                                                                @csrf
                                                                @method('delete')
                                                                <button class="btn btn-danger" href="">Xoá</button>
                                                            </form>

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </tr>

                                    @endforeach

                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th scope="col">STT</th>
                                        <th scope="col" class="text-center">Ảnh</th>
                                        <th scope="col">Tên sản phẩm</th>
                                        <th scope="col">Loại sản phẩm</th>
                                        <th scope="col">Giá sản phẩm</th>
                                        <th scope="col">Giá khuyến mãi</th>
                                        <th scope="col">Thao tác</th>
                                    </tr>

                                </tfoot>
                            </table>
                            <ul class="pagination justify-content-end">
                                @php
                                    $totalPage = $responseData['last_page'];
                                    $currentPage = $responseData['current_page'];

                                @endphp
                                <li class="page-item"><a class="page-link" href="#">Trước</a></li>
                                @for ($i = 1; $i <= $totalPage; $i++)
                                    <li class="page-item @if ($i==$currentPage) {{ 'active' }} @endif"><a class="page-link"
                                            href="{{ route('admin.product.page', $i) }}">{{ $i }}</a>
                                    </li>
                                @endfor
                                <li class="page-item"><a class="page-link" href="#">Sau</a></li>
                            </ul>
                        </div>
                        <!-- /.card-body -->
                    </div>

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>

@endsection