routes/web.php
<?php

use Illuminate\Support\Facades\Route;
// Route::namespace('Admin')->group(function(){
//     route::get('admin',function(){
//         return 1;
//     });
// });

Route::namespace('Site')->group(function () {
    Route::get('/login', 'UserController@login')->name('site.login');
    Route::post('/login', 'UserController@login')->name('site.login');
    Route::post('/logout', 'UserController@logout')->name('site.logout');
    Route::get('/register', 'UserController@register')->name('site.register');
    Route::post('/register', 'UserController@register')->name('site.register');

    Route::get('/', 'HomeController@index')->name('home');

    Route::get('/danh-muc-bai-viet/{slug}', 'ContentController@categoryContent')->name('categoryContent');
    Route::get('/chi-tiet-bai-viet/{slug}', 'ContentController@detailContent')->name('detailContent');
    Route::get('/page/{page_id}', 'HomeController@page')->name('home.page');
    Route::get('/tim-kiem', 'ProductController@search')->name('search');
    Route::get('/listProductByCategory/{category_slug}', 'ProductController@listProductByCategory')->name('product');
    Route::get('/productDetail/{slug}', 'ProductController@productDetail')->name('detailProduct');
    Route::get('/certificate', 'CertificateController@index')->name('certificate');
    Route::get('/detailCertificate/{certificate_slug}', 'CertificateController@detailCertificate')->name('detailCertificate');
    Route::get('/feedback', 'FeedbackController@index')->name('feedback');
    Route::get('/list-file', 'HomeController@listFile')->name('file');
    Route::get('/video', 'HomeController@listVideo')->name('video');
    Route::get('/quang-cao', 'QcController@index')->name('qc');
    Route::get('/chi-tiet-quang-cao/{id}', 'QcController@detailQc')->name('detailQc');
});
Route::namespace('Admin')->prefix('admin')->group(function () {
    Route::get('/login', 'LoginController@view')->name('login');
    Route::post('/logout', 'LoginController@logout')->name('admin.logout');
    Route::post('/checkLogin', 'LoginController@checkLogin')->name('checkLogin');
    Route::get('/logOut', 'LoginController@logout')->name('logout');
});

Route::prefix('admin')->namespace('Admin')->name('admin.')->middleware('checkLoginAdmin')->group(function () {

    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/page/{page_id}', 'PageController@page')->name('page');
    Route::get('/nextPage/{page_id}', 'PageController@nextPage')->name('nextPage');
    Route::get('/prevPage/{page_id}', 'PageController@prevPage')->name('prevPage');

    Route::prefix('categoryProduct')->name('categoryProduct.')->group(function () {
        Route::get('/', 'CategoryProductController@index')->name('index');
        Route::get('/edit/{categoryProduct_id}', 'CategoryProductController@edit')->name('edit');
        Route::post('/store', 'CategoryProductController@store')->name('store');
        Route::PUT('/update/{categoryProduct_id}', 'CategoryProductController@update')->name('update');
        Route::delete('/delete/{categoryProduct_id}', 'CategoryProductController@delete')->name('delete');
    });
    Route::prefix('product')->name('product.')->group(function () {
        Route::get('/', 'ProductController@index')->name('index');
        Route::get('/create', 'ProductController@create')->name('create');
        Route::get('/edit/{product_id}', 'ProductController@edit')->name('edit');
        Route::get('/page/{page_id}', 'ProductController@page')->name('page');
        Route::post('/store', 'ProductController@store')->name('store');
        Route::post('/storeAddInCategory/{category_id}', 'ProductController@storeAddInCategory')->name('storeAddInCategory');

        Route::PUT('/update/{product_id}', 'ProductController@update')->name('update');
        Route::delete('/delete/{product_id}', 'ProductController@delete')->name('delete');
    });


    Route::prefix('categoryContent')->name('categoryContent.')->group(function () {
        Route::get('/', 'CategoryContentController@index')->name('index');
        Route::get('/edit/{categoryContent_id}', 'CategoryContentController@edit')->name('edit');
        Route::post('/store', 'CategoryContentController@store')->name('store');
        Route::PUT('/update/{categoryContent_id}', 'CategoryContentController@update')->name('update');
        Route::delete('/delete/{categoryContent_id}', 'CategoryContentController@delete')->name('delete');
    });
    Route::prefix('content')->name('content.')->group(function () {
        Route::get('/', 'ContentController@index')->name('index');
        Route::get('/create', 'ContentController@create')->name('create');
        Route::get('/edit/{Content_id}', 'ContentController@edit')->name('edit');
        Route::get('/page/{page_id}', 'ContentController@page')->name('page');
        Route::post('/store', 'ContentController@store')->name('store');
        Route::post('/storeAddInCategory/{category_id}', 'ContentController@storeAddInCategory')->name('storeAddInCategory');

        Route::PUT('/update/{Content_id}', 'ContentController@update')->name('update');
        Route::delete('/delete/{Content_id}', 'ContentController@delete')->name('delete');
    });

    Route::prefix('certificate')->name('certificate.')->group(function () {
        Route::get('/', 'CertificateController@index')->name('index');
        Route::get('/page/{page_id}', 'CertificateController@page')->name('page');
        Route::get('/create', 'CertificateController@create')->name('create');
        Route::get('/edit/{certificate_id}', 'CertificateController@edit')->name('edit');
        Route::get('/editItem/{item_id}', 'CertificateController@editItem')->name('editItem');
        Route::post('/store', 'CertificateController@store')->name('store');
        Route::post('/addItem', 'CertificateController@addItem')->name('addItem');
        Route::PUT('/update/{certificate_id}', 'CertificateController@update')->name('update');
        Route::PUT('/updateItem/{item_id}', 'CertificateController@updateItem')->name('updateItem');
        Route::delete('/delete/{certificate_id}', 'CertificateController@delete')->name('delete');
        Route::delete('/deleteItem/{item_id}', 'CertificateController@deleteItem')->name('deleteItem');
    });
    Route::prefix('feedback')->name('feedback.')->group(function () {
        Route::get('/', 'FeedbackController@index')->name('index');
        Route::get('/page/{page_id}', 'FeedbackController@page')->name('page');

        Route::get('/edit/{feedback_id}', 'FeedbackController@edit')->name('edit');
        Route::post('/store', 'FeedbackController@store')->name('store');
        Route::PUT('/update/{feedback_id}', 'FeedbackController@update')->name('update');
        Route::delete('/delete/{feedback_id}', 'FeedbackController@delete')->name('delete');
    });
    Route::prefix('file')->name('file.')->group(function () {
        Route::get('/', 'FileController@index')->name('index');
        Route::get('/page/{page_id}', 'FileController@page')->name('page');

        Route::get('/edit/{id}', 'FileController@edit')->name('edit');
        Route::get('/edit-file/{id}', 'FileController@editFile')->name('edit_file');
        Route::post('/store', 'FileController@store')->name('store');
        Route::post('/store-file', 'FileController@storeFile')->name('store_file');
        Route::PUT('/update/{id}', 'FileController@update')->name('update');
        Route::PUT('/update-file/{id}', 'FileController@updateFile')->name('update_file');
        Route::delete('/delete/{id}', 'FileController@delete')->name('delete');
        Route::delete('/delete-file/{id}', 'FileController@deleteFile')->name('delete_file');
        Route::get('/list-file/{category_file_id}', 'FileController@listFile')->name('list_file');
    });
    Route::prefix('video')->name('video.')->group(function () {
        Route::get('/', 'VideoController@index')->name('index');
        Route::get('/edit/{id}', 'VideoController@edit')->name('edit');
        Route::post('/store', 'VideoController@store')->name('store');
        Route::PUT('/update/{id}', 'VideoController@update')->name('update');
        Route::delete('/delete/{id}', 'VideoController@delete')->name('delete');
    });
    Route::prefix('adv')->name('advertisement.')->group(function () {
        Route::get('/', 'AdvController@index')->name('index');
        Route::get('/edit/{id}', 'AdvController@edit')->name('edit');
        Route::post('/store', 'AdvController@store')->name('store');
        Route::PUT('/update/{id}', 'AdvController@update')->name('update');
        Route::delete('/delete/{id}', 'AdvController@delete')->name('delete');
    });

    Route::prefix('slider')->name('slider.')->group(function () {
        Route::get('/', 'SliderController@index')->name('index');
        Route::get('/edit/{slider_id}', 'SliderController@edit')->name('edit');
        Route::post('/store', 'SliderController@store')->name('store');
        Route::PUT('/update/{slider_id}', 'SliderController@update')->name('update');
        Route::PUT('/active/{slider_id}', 'SliderController@active')->name('active');
        Route::delete('/delete/{slider_id}', 'SliderController@delete')->name('delete');
    });
    Route::prefix('setting')->name('setting.')->group(function () {
        Route::get('/', 'SettingController@index')->name('index');
        Route::post('/store', 'SettingController@store')->name('store');
    });
});
// Route::get('/video', function () {
//     return view('site.video');
// })->name('video');
// Route::get('/quang-cao', function () {
//     return view('site.qc');
// })->name('qc');

app/Http/Controllers/Admin/SettingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Helpers\Helpers;
use App\Http\Controllers\Controller;
use App\Http\Controllers\ControllerBase;
use GuzzleHttp\Client;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Cookie;

class SettingController extends ControllerBase
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        // try {

        $token = Cookie::get('tokenLogin');
        if (!$token) {
            alert()->error('Tài khoản đã hết phiên đăng nhập');

            return redirect()->route('admin.login');
        }
        $client = new Client();
        $data = $client->get($this->urlAPI() . "admin/setting", [
            'headers' => [
                'Authorization' => 'Bearer ' .  $token,
                'Accept' => 'application/json',
            ],
        ]);
        $response = json_decode($data->getBody()->getContents(), true);
        $infor = $response['data'];

        return view('admin.setting.index', compact(
            'infor',
        ));
        // } catch (\Throwable $th) {
        //     alert($th)->error('Hệ thống đang được bảo trì. Vui lòng thử lại sau!');
        //     return back();
        // }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        try {
            $token = $request->cookie('tokenLogin');
            if (!$token) {
                alert()->error('Tài khoản đã hết phiên đăng nhập');
                return redirect()->route('admin.login');
            }
            $dataSend = Helpers::dataSend($request);
            $url = $this->urlAPI() . 'admin/setting/store';
            $client = new Client([
                'headers' => [
                    'Authorization' => 'Bearer ' .  $token,
                    'Content-Type' => 'application/json',
                ],
            ]);
            $req = $client->post(
                $url,
                [
                    'multipart' => $dataSend,

                ],
                // ['form_params']
            );
            $response = json_decode($req->getBody()->getContents(), true);
            if ($response['status'] == 1) {

                alert()->success($response['message']);
                return redirect()->route('admin.setting.index');
            } else {
                alert()->error($response['message']);
                return back();
            }
        } catch (\Throwable $th) {
            alert($th)->error('Hệ thống đang được bảo trì. Vui lòng thử lại sau!');
            return back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/setting/index.blade.php
@extends('admin.layouts.app')
@section('title-page', 'Cài đặt thông tin website')
@section('after-css')
    <link rel="stylesheet" href="{{ asset('template/AdminLTE/plugins/summernote/summernote-bs4.min.css') }}">
@endsection
@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header d-flex align-items-center justify-content-between">
                            <h3 class="card-title">Cài đặt thông tin website</h3>


                        </div>
                        <!-- /.card-header -->
                        <div class="row">
                            <div class="offset-md-2"></div>
                            <div class="col-12 col-md-8">
                                <div class="card-body">
                                    <form action="{{ route('admin.setting.store') }}" method="post"
                                        enctype="multipart/form-data">
                                        @csrf
                                        <div class="form-group">
                                            <label class="form-label">Email webiste </label>
                                            <input name="email" placeholder="Email webiste ..." type="text"
                                                value="{{ $infor['email'] }}" class="form-control" value="">
                                        </div>
                                        <div class="form-group">
                                            <label class="form-label">Số điện thoại website</label>
                                            <input name="phone" placeholder="Số điện thoại website ..." type="text"
                                                class="form-control" value="{{ $infor['phone'] }}">
                                        </div>
                                        <div class="form-group">
                                            <label class="form-label">Địa chỉ cửa hàng</label>
                                            <input name="address" placeholder="Địa chỉ cửa hàng ..." type="text"
                                                class="form-control" value="{{ $infor['address'] }}">
                                        </div>
                                        <div class="form-group">
                                            <label class="form-label">Link trang Facebook </label>
                                            <input name="fb_ref" placeholder="Link trang Facebook ..." type="text"
                                                class="form-control" value="{{ $infor['fb_ref'] }}">
                                        </div>
                                        <div class="form-group">
                                            <label class="form-label">Mã số Page Facebook(Add chat message)</label>
                                            <label class="form-label"><a href="https://lucidgen.com/cach-nhung-messenger-vao-website" target="_blank">Hướng dẫn thêm tên miền website vào phần Miền trang web </a></label>

                                            <input name="page_id" placeholder="Mã số Page Facebook(Add chat message) ..."
                                                type="text" class="form-control" value="{{ $infor['fb_page_id'] }}">

                                        </div>
                                        <div class="form-group">
                                            <label class="form-label">Bản quyền website</label>
                                            <input name="copyright" placeholder="Bản quyền website ..." type="text"
                                                class="form-control" value="{{ $infor['copyright'] }}">
                                        </div>
                                        <div class="form-group">
                                            <label class="form-label">Giới thiệu website(footer)</label>
                                            <textarea name="introduce" id=""  class="form-control" placeholder="Giới thiệu website(footer)..." rows="4">
                                                {{ $infor['introduce'] }}
                                            </textarea>
                                            {{-- <input name="introduce" placeholder="Giới thiệu website ..." type="text"
                                                class="form-control" value="{{ $infor['introduce'] }}"> --}}
                                        </div>
                                        <div class="form-group">
                                            <label for="">Logo</label>
                                            <input type="file" class="form-control imageInput" name="logo"
                                                placeholder="Logo">
                                            <div class="d-flex mt-4 justify-content-center align-items-center">
                                                <img src="{{ $infor['logo'] }}" width="240" class="image-preview " alt="">
                                            </div>
                                        </div>
                                        <div class="col-12 text-center">
                                            <button type="submit" class="btn btn-primary">Cập nhật</button>

                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>

                        <!-- /.card-body -->
                    </div>

                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>

@endsection

@section('after-scripts')

    <script>
        $(function() {

            $('.imageInput').on('change', function() {
                $input = $(this);
                if ($input.val().length > 0) {
                    fileReader = new FileReader();
                    fileReader.onload = function(data) {
                        $('.image-preview').attr('src', data.target.result);
                    }
                    fileReader.readAsDataURL($input.prop('files')[0]);
                }
            });
        })
    </script>

@endsection